# Generated by Django 5.1.3 on 2024-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activitylog_delete_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.CharField(max_length=255, verbose_name=models.DateTimeField(auto_now_add=True)),
        ),
    ]
